### ISSUE TITLE
running on custom detections

### ISSUE THREAD

**Issue by andreaceruti** [cheind/py-globalflow#1]
Hi, I would like to know if it is possible to use this method with detections already provided by my trained detector.
I have simply trained a maskrcnn on my object (grape bunches, so it is not in the common datasets used).
Then I decompose a video representing a vineyard row in multiple frame and I generate the detections for each frame, saving them to a json file.
How would I pass these detections to the algorithm? 
Since I have RGB-D data, is it possible to define some sort of cost function using the depth map?

**Comment by SkepticRaven** [comment]
Don't know if you still haven't figured this out, but I just ran into this repo and found it to be pretty useful.
While the docs don't describe specifically how to redefine the loss, here's my notes (which may be useful to others that don't know how) on how I was able to do it.

The key area in the README.md is changing the observation data you send into the graph and the transition_cost function.
In my use-case, I have a high dimensional point in the observation data which I want to link together things with a smaller cosine distance.

Sending the observations into the nodes is straight forward, since it will accept arbitrary data. Observations are in a format of a list of lists. First list is the time dimension, second list is the observation dimension. I haven't tested it, but I suspect you can pass arbitrary objects (eg a custom class) into the observations since it worked out of the box with me switching the example scalar data with list data.

```
timeseries = [
	[[0.0,2.0,1.2], [1.0, 0.0, 1.0]],  # 2 observations at t=0
	[[-0.1, 0.0, 1.2]],  # 1 observation at at t=1
	...
]
```

After that, the transition cost definition would look something like this. Note that everything in the observation is now accessible as x.obs and y.obs.

```
def transition_cost(self, x: gflow.FlowNode, y: gflow.FlowNode) -> float:
	tdiff = y.time_index - x.time_index
	# We can just log transform the cosine distances
	# Cosine distance should be from range 0-1
	# We also add 0.1 in between time steps to penalize linking items further in time
	logprob = np.log(scipy.spatial.distance.cdist([x.obs], [y.obs], metric='cosine') + 0.1 * tdiff)
	return logprob
```

I can't help with RGB-D cost function, but hopefully this helps with how one would add their own costs and pass different observation data. You may also need to be careful about how you scale the costs because as noted in the paper this was based on, the cost of matching observations is compared against cost of being a new observation (penter) and cost of being a final observation (pexit).

**Comment by cheind** [comment]
Very nice, thanks a lot! I have developed this code for a specific use case and then forgot about generalizing it for other use cases. In fact, I need to revisit it for another project and your docs will help me getting started again :)
